### ISSUE TITLE
Setup a Database for the raspberry pi

### ISSUE THREAD

**Issue by jygh98** [erdl/sensors#30]

**Comment by carlosparadis** [comment]
@jygh98: Since @matthew-schultz will get around creating a database for the other sensors on task 6, and you have as priority having everything running first, I am re-assigning this to him.

@matthew-schultz You can safely ignore this issue until you are done with the entire issue #25. Ask me or @ryantanaka if you need more context about this out of curiosity, but does not interfere with your current work.

**Comment by ryantanaka** [comment]
@carlosparadis, just want to confirm where this will be (eg ERDL desktop, IT-VM, the linux box that matt is currently using, etc.) 

I'm guessing we will test this locally, THEN the database should eventually be set up in the IT-VM once all the kinks have been ironed out in terms of the pi's working properly.

**Comment by carlosparadis** [comment]
@ryantanaka yes, all the dev for now will go on the local server in ERDL. We will discuss moving all this effort to production later on and open a dedicated issue for "migration".

**Comment by carlosparadis** [comment]
I'm closing this, as at the time replace Scrape-utils was not on the table. If the need arises, we should open a new issue to integrate to this Github project.
