### ISSUE TITLE
Documentation of the UHM Frog Dashboard Kiosk

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/sensors#6]
We don't know where to post this. @kathrynparadis  and @ryantanaka  understand we need this documentation. The large touch screens in the UHM Frog buildings are connected to chromeboxes and use a kiosk app to lock it to a url http://uhmfrogbackend.herokuapp.com/static/west_main.html  and some documentation can be found on https://github.com/fspmarshall/kiosk   Kat can give this a shot first.

**Comment by carlosparadis** [comment]
@eileenpeppard when you don't know where to post, it is best to send an e-mail asking than post at random somewhere on Github asking since we can't delete them, just flag as duplicates and close (hence making harder to find things on the long-run). 

[This issue](https://github.com/erdl/survey_display/issues/3) is very likely what you are looking for to continue on (please see the diagrams there), so I am closing this issue and we can continue the discussion there.

Also, this project is for sensors (as the name suggests), UHM Frog Dashboard is `survey_display` as the kiosk itself only uses `survey_display`.
